### ISSUE TITLE
Definitions File Distribution

### ISSUE THREAD

**Issue by jojotastic777** [Aeomi/AeTypeFall#1]
Instead of distributing a seperate definitions file here, consider distributing a script to pull/update the definitions file from [here.](https://github.com/Aeomi/TypeFall-Definitions)

**Comment by Ehntae** [comment]
A good idea. I was thinking instead that this repo should serve to provide relevant, or derivative definitions for typefall.

**Comment by Ehntae** [comment]
I will likely pull the core definitions file from the repo when the user uses the "npm i" command.
